spring.application.name=terrius

# application-secret.properties
spring.config.import=optional:application-secret.properties

# Datasource
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# OAuth2
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT}
spring.security.oauth2.client.registration.kakao.client-authentication-method=none
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri=${KAKAO_REDIRECT_URI}
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image,account_email
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
frontend.oauth-callback-uri=${FRONTEND_OAUTH_CALLBACK_URI:http://localhost:5173/oauth/callback}

# JWT
jwt.secret = ${JWT_SECRET_KEY}
jwt.access.token.validity = ${JWT_ACCESS_TOKEN_TIME}
